version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - jads-network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - jads-network

  db-payments:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: admin123
       MYSQL_DATABASE: payments
       MYSQL_USER: docker
       MYSQL_PASSWORD: admin123
       MYSQL_ROOT_HOST: '%'
       MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - jads-network
      
  payments:
      restart: always
      build:
         context: .
         dockerfile: Dockerfile
      environment:
         SPRING.DATASOURCE.URL: jdbc:mysql://db-payments:3308/payments?useTimezone=true&serverTimezone=UTC
         SPRING.DATASOURCE.USERNAME: root
         SPRING.DATASOURCE.PASSWORD: admin123
         SPRING.KAFKA.PRODUCER.BOOTSTRAP-SERVERS: kafka:9092
         SPRING.KAFKA.CONSUMER.BOOTSTRAP-SERVERS: kafka:9092
      ports:
         - 8099:8099
      depends_on:
         - db-payments
         - kafka
      networks:
         - jads-network

networks:
  jads-network:
    driver: bridge