server:
   port: 8099

spring:
   application:
      name: payments
   datasource:
      url: jdbc:mysql://localhost:3306/payments?useTimezone=true&serverTimezone=UTC
      username: root
      password: postgres
      driverClassName: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl_auto: update
   kafka:
      producer:
         bootstrap-servers: localhost:29092
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: com.github.serializer.NotificationSerializer
      consumer:
         bootstrap-servers: localhost:29092
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: com.github.deserializer.NotificationDeserializer

api:
   authorization: https://util.devi.tools/api/v2/authorize
   notification: https://util.devi.tools/api/v1/notify

